### PR TITLE
Fix Ecto 3.0 warnings

### LINKED ISSUE #102: Ecto 3.0 emits warnings when using arc_ecto
When using Ecto 3.0 and arc_ecto, I see a lot of warnings about arc_ecto passing strings into `cast()` as the allowed list of param keys.

image

Here are the ecto versions in my mix.lock

```
"ecto": {:hex, :ecto, "3.0.1", "a26605ee7b243a754e6609d1c23da27bcb22823659b07bf03f9020da92a8e4f4" ....
"ecto_sql": {:hex, :ecto_sql, "3.0.0", "8d1883376bee02a0e76b5ef797e39d04333c34b9935d0b4785dbf3cbdb571e2a" ....
```

### PR DESCRIPTION
**Pull request by dbernheisel**
Fixes #102. Related #98 #99 #101. Same work is done in #101 and #99, except this PR doesn't bump the ecto requirement or use the formatter.

I didn't find it necessary to update the project's Ecto requirement. This should continue to work fine with Ecto 2.x, as well as silence the errors emitted with Ecto 3.x. I've tested this locally.

Sidenotes:
- Also suppressed logs when running tests. I'd be happy to assert the log output if that's the intention. Otherwise it was only polluting the stdout when running tests.

### CODE REVIEW

File: lib/arc_ecto/schema.ex [hunk 1]
```diff
@@ -18,7 +18,7 @@ defmodule Arc.Ecto.Schema do
       end
 
       # Cast supports both atom and string keys, ensure we're matching on both.
-      allowed = Enum.map(allowed, fn key ->
```
Comment (dbernheisel) [inline lib/arc_ecto/schema.ex]: this reassigned the keys passed in from `cast_attachment()` which are atoms.

**Comment by williamweckl** [comment]
I opened an issue at arc repository about the error logs.
https://github.com/stavro/arc/issues/268

Do you think this PR will solve it too?

By the way, thanks for the amazing job!

**Comment by whitepaperclip** [comment]
Any chance this gets merged soon? Has the project been abandoned?
